spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  session:
    store-type: redis
  jpa:
    hibernate:
      show-sql: ${spring.jpa.hibernate.show_sql}
      ddl-auto: ${spring.jpa.hibernate.ddl_auto}
    ##database-platform: org.hibernate.dialect.MySQLDialect
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driverClassName: ${spring.datasource.driverClassName}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: ${server.port}
  servlet:
    context-path: /

logging:
  level:
    root: ${logging.level.root}
